name: Build and Test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .gitignore
      - .idea
      - .editorconfig
      - docker-compose.yml
      - README.md
      - ../../dev.env
  pull_request:
    paths-ignore:
      - .gitignore
      - .idea
      - .editorconfig
      - docker-compose.yml
      - README.md
      - ../../dev.env

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  packages: write

jobs:
  extract-vars:
    name: Extract Variables from Taskfile
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.extract.outputs.GO_VERSION }}
      golangci-lint-version: ${{ steps.extract.outputs.GOLANGCI_LINT_VERSION }}
      modules: ${{ steps.extract.outputs.MODULES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Extract variables from Taskfile
        id: extract
        run: |
          chmod +x .github/scripts/extract-versions.sh
          .github/scripts/extract-versions.sh
  lint:
    needs: extract-vars
    uses: ./.github/workflows/lint-reusable.yaml
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}
      golangci-lint-version: ${{ needs.extract-vars.outputs.golangci-lint-version }}

  test:
    uses: ./.github/workflows/test-reusable.yaml
    needs: lint
    with:
      modules: ${{ needs.extract-vars.outputs.modules }}
      go-version: ${{ needs.extract-vars.outputs.go-version }}